[package]
name = "rsfilename"
license = "MIT"
version = "0.1.0"
edition = "2021"
description = "Windows-proof safe file name generator."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
